name: End-to-End

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:3.4.23
        ports:
          - '27017-27019:27017-27019'

    steps:
    - uses: actions/checkout@v1

    - name: Seed database
      run: ./mongoseed.sh
      working-directory: ./database

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run e2e tests
      uses: cypress-io/github-action@v2
      with:
        start: cd ../server && ./gradlew run
        command: npm run e2e
        working-directory: ./phone-store


