name: "Update Angular"
on: # when the action should run. Can also be a CRON or in response to external events. see https://git.io/JeBz1
  schedule:
    - cron: '0 5 1 * *'
  workflow_dispatch:

jobs:
  ngxUptodate:
    runs-on: ubuntu-latest
    steps:
      - name: Updating ng dependencies # the magic happens here !
        uses: fast-facts/ng-update@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
