name: Server Java

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4.3
        ports:
          - '27017-27019:27017-27019'

    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./server
